name: Test and lint-check
on: push
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with: 
                cache: npm
            - name: install
              run: make install
            - name: tests
              run: make test
            - name: coverage
              run: make test-coverage
            - name: lint
              run: make lint